# Generated by Django 4.2.11 on 2026-04-13 21:36

import albums.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_alter_album_cover_image_alter_sticker_image_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=albums.models.album_cover_upload),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='image_reference',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=albums.models.sticker_image_upload),
        ),
    ]
