# Generated by Django 4.2.11 on 2026-04-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_alter_album_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
