# Generated by Django 6.0.4 on 2026-04-18 20:47

import albums.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0007_stickerreferencephoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='custom_prompt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='stickerreferencephoto',
            name='photo',
            field=models.ImageField(max_length=255, upload_to=albums.models._ref_photo_upload),
        ),
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, max_length=255, null=True, upload_to=albums.models._scan_log_upload)),
                ('ai_response', models.JSONField(blank=True, default=dict)),
                ('detected_items', models.CharField(blank=True, default='', max_length=500)),
                ('matched', models.BooleanField(default=False)),
                ('confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_sticker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_logs', to='albums.sticker')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
