# Generated by Django 4.2.11 on 2026-06-01 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0010_vision_cache_circuit_breaker'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='scanquotausage',
            new_name='albums_scan_user_id_4eaf0c_idx',
            old_name='albums_scan_user_id_date_idx',
        ),
        migrations.RenameIndex(
            model_name='visionresultcache',
            new_name='albums_visi_phash_206725_idx',
            old_name='albums_visi_phash_idx',
        ),
    ]
